### PR TITLE
Add where param to masterdata scroll documents function

### PR DESCRIPTION
**Pull request by gabrielHosino**
#### What is the purpose of this pull request?

This PR adds the param `where` to the scrollDocuments method of the MD client. Looking in the docs and making some tests on postman, shows that the scroll method should have the `where` param to filter the data just as the search method 

#### Types of changes

* [x] Bug fix (a non-breaking change which fixes an issue)
* [ ] New feature (a non-breaking change which adds functionality)
* [ ] Breaking change (fix or feature that would cause existing functionality to change)
* [ ] Requires change to documentation, which has been updated accordingly.

### CODE REVIEW

**Comment by gabrielHosino** [comment]
@vtex/composable-commerce-sq4 Can someone help me with this please? 🥺

**Comment by carlosmonteiro** [comment]
@ygorops

**Review by valentino-amadeus — APPROVED** [review]

**Comment by gabrielHosino** [comment]
@valentino-amadeus Thanks, should I update the changelog and version before the merge? Or just the changelog?

**Comment by valentino-amadeus** [comment]
@gabrielHosino, please update both the changelog and the version.

**Comment by gabrielHosino** [comment]
@valentino-amadeus Thanks! Done!

**Review by GustavoMA — APPROVED** [review]
LGTM

**Comment by gabrielHosino** [comment]
@valentino-amadeus Can i merge the PR? Or do you prefer to merge when you are releasing a new version?

**Comment by valentino-amadeus** [comment]
I am going to merge it when I deploy it.
I'll do it today!

**Comment by valentino-amadeus** [comment]
Guys, we are on defcon 2. 
The `@vtex/composable-commerce` team will deploy this change as soon as we get out of it.

**Pull request merged**
