### PR TITLE
Create a client for metadata

### PR DESCRIPTION
**Pull request by igorframos**

### CODE REVIEW

**Comment by firstdoit** [comment]
This LGTM buuut now it needs to be re-written as TypeScript! You can thank @brunoabreu 😂

**Comment by igorframos** [comment]
I kinda brought this on myself when I asked about types in this project being imported into another one. 😰

**Comment by igorframos** [comment]
Done. PTAL, @firstdoit.

**Comment by brunoabreu** [comment]
@igorframos I'm missing the type definitions for `getBuckets`, `list`, `listAll` and `get` methods.

**Pull request merged**
